return PlaceObj('ModDef', {
	'title', "SMR Community Fixes",
	'description', "A community-maintained collection of bug fixes for Surviving Mars: Relaunched.\n\n[Beta] indicates that a fix still requires further testing.\n\nAccess it from:\n\nMain Menu -> Options -> SMR Community Fixes\n\nCurrent fixes/attempts:\n\nRestore Disasters — Clears stale Meteor Storm state that can block disasters, rain, terraforming expeditions, and Inner Light events.\nRestore Rains — Restarts natural and Cloud Seeding rain when its scheduling or saved state becomes stale.\n[Beta] Restore Dust Devils — Corrects Dust Devil spawning and surface-map scheduling, and prevents new Dust Devils after terraforming disables Dust Storms.\n[Beta] Restore Asteroid Visits — Prevents ordinary rockets from being incorrectly treated as asteroid landers.\n[Beta] Restore Soil Overlay — Keeps the soil overlay associated with the surface map when another map is active.\n[Beta] Restore Saint Blessing — Correctly applies each Saint’s stacking Morale bonus to Religious colonists in the same Dome.\n[Beta] Restore SpaceY Description — Adds SpaceY’s missing +20 maximum Drone Hub capacity benefit to its description.\n[Beta] Restore Jumbo Cave Reinforcements — Releases construction sites that become stuck because of unreachable Waste Rock.\n[Beta] Restore No Disasters Cave-in Protection — Prevents periodic underground Marsquakes and cave-ins when No Disasters is enabled.\n[Beta] Restore Trade Rocket Protection — Prevents RC Transports from interrupting Universal Trade Rockets.\n[Beta] Restore Asteroid Lander Cargo Safety — Prevents payload changes while Drones or passengers are using an asteroid lander’s ramp.\n[Beta] Restore Localized UI Text — Restores the official translations for the terraforming heading and Universal Rocket action.\n[Beta] Restore Track Demolition — Completes terminal track demolition and removes invalid Track remnants from existing saves.\n[Beta] Restore Clustered Lights — Stops night lights entering the renderer in a compressed burst that can trigger the clustered-light assertion.\n[Beta] Restore Mod Screenshots — Shows a mod's screenshots in the Paradox Mods browser instead of two errors and no pictures.\n[Beta] Restore Mod Details — Refreshes thumbnails throughout the Paradox Mods browser and restores website-style formatted descriptions.",
	'short_description', "A community-maintained collection of bug fixes for Surviving Mars: Relaunched.",
	'image', "Mod/SMRCF/Images/smr_community_fixes.jpg",
	'last_changes', "Restore Mod Details: refine first-render thumbnails and formatted bold text.",
	'id', "SMRCF",
	'author', "SMR-community",
	'version', 9,
	'lua_revision', 350453,
	'saved_with_revision', 392284,
	'code', {
		"Code/SMRCommunityFixes.lua",
		"Code/smrcf_restore_disasters.lua",
		"Code/smrcf_restore_rains.lua",
		"Code/smrcf_restore_dust_devils.lua",
		"Code/smrcf_restore_asteroid_visits.lua",
		"Code/smrcf_restore_soil_overlay.lua",
		"Code/smrcf_restore_saint_blessing.lua",
		"Code/smrcf_restore_spacey_description.lua",
		"Code/smrcf_restore_jumbo_cave.lua",
		"Code/smrcf_restore_no_disasters_cave_ins.lua",
		"Code/smrcf_restore_trade_rocket_protection.lua",
		"Code/smrcf_restore_asteroid_lander_cargo_safety.lua",
		"Code/smrcf_restore_localized_ui_text.lua",
		"Code/smrcf_restore_track_demolition.lua",
		"Code/smrcf_restore_clustered_lights.lua",
		"Code/smrcf_restore_mod_screenshots.lua",
		"Code/smrcf_restore_mod_details.lua",
	},
	'saved', 1785879519,
	'code_hash', -508764141081500062,
	'pdx_id', 154004,
	'pdx_version', "1",
	'TagGameplay', true,
	'TagOther', true,
})
